# Generated by Django 6.0.4 on 2026-05-19 10:36

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioScenario',
            fields=[
                ('audio_scenario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'audio_scenarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaceFeatureVector',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.PositiveIntegerField()),
                ('face_landmarks', models.JSONField(blank=True, null=True)),
                ('emotion_scores', models.JSONField(blank=True, null=True)),
                ('head_pose', models.JSONField(blank=True, null=True)),
                ('eye_tracking', models.JSONField(blank=True, null=True)),
                ('blink_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('api_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'face_feature_vectors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhonationSession',
            fields=[
                ('phonation_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phonation_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhonationSound',
            fields=[
                ('sound_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('sound_character', models.CharField(max_length=50)),
                ('sound_name', models.CharField(max_length=255)),
                ('sound_order', models.IntegerField()),
            ],
            options={
                'db_table': 'phonation_sounds',
                'ordering': ['sound_order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TextParameterResult',
            fields=[
                ('text_parameter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emotion_distribution', models.JSONField(blank=True, null=True)),
                ('keyword_analysis', models.JSONField(blank=True, null=True)),
                ('linguistic_features', models.JSONField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'text_parameter_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoActivity',
            fields=[
                ('video_activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('instruction_text', models.TextField()),
                ('image_set_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'video_activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiApiRegistry',
            fields=[
                ('api_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=255, unique=True)),
                ('service_type', models.CharField(max_length=100)),
                ('base_url', models.TextField()),
                ('port', models.IntegerField(blank=True, null=True, unique=True)),
                ('endpoint_path', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('health_status', models.CharField(default='healthy', max_length=50)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_api_registry',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('timeout_seconds__gt', 0)), name='api_timeout_seconds_gt_0'), models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='api_retry_count_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacialAnalysisResult',
            fields=[
                ('facial_analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anxiety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('risk_label', models.CharField(blank=True, max_length=100, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.OneToOneField(db_column='feature_id', on_delete=django.db.models.deletion.CASCADE, related_name='facial_analysis_result', to='mindspace.facefeaturevector')),
            ],
            options={
                'db_table': 'facial_analysis_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('activity_video', 'Activity Video'), ('phonation_audio', 'Phonation Audio'), ('scenario_audio', 'Scenario Audio'), ('image', 'Image')], max_length=30)),
                ('file_name', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_provider', models.CharField(default='gcp', max_length=50)),
                ('bucket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_region', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_class', models.CharField(blank=True, max_length=100, null=True)),
                ('object_key', models.TextField()),
                ('cdn_url', models.TextField(blank=True, null=True)),
                ('checksum_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_assets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhonationAttempt',
            fields=[
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pronunciation_detected', models.BooleanField(blank=True, null=True)),
                ('character_accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('noise_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('silence_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.PROTECT, related_name='phonation_attempts', to='mindspace.mediaasset')),
                ('phonation_session', models.ForeignKey(db_column='phonation_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mindspace.phonationsession')),
                ('sound', models.ForeignKey(db_column='sound_id', on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='mindspace.phonationsound')),
            ],
            options={
                'db_table': 'phonation_attempts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioExtractionResult',
            fields=[
                ('audio_extraction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_wave_features', models.JSONField(blank=True, null=True)),
                ('noise_profile', models.JSONField(blank=True, null=True)),
                ('frequency_profile', models.JSONField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, related_name='audio_extraction_result', to='mindspace.phonationattempt')),
            ],
            options={
                'db_table': 'audio_extraction_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhonationFeature',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_mean', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('jitter', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('shimmer', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('hnr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('voice_energy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mfcc_features', models.JSONField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_extraction', models.OneToOneField(db_column='audio_extraction_id', on_delete=django.db.models.deletion.CASCADE, related_name='phonation_feature', to='mindspace.audioextractionresult')),
            ],
            options={
                'db_table': 'phonation_features',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlatformScreeningSession',
            fields=[
                ('screening_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('current_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_stage', models.PositiveIntegerField(default=1)),
                ('completed_activities_count', models.PositiveIntegerField(default=0)),
                ('overall_risk', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_screening_sessions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='phonationsession',
            name='screening_session',
            field=models.OneToOneField(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='phonation_session', to='mindspace.platformscreeningsession'),
        ),
        migrations.CreateModel(
            name='PcaPipelineResult',
            fields=[
                ('pca_result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reduced_feature_vector', pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True)),
                ('dimensionality_reduction_metadata', models.JSONField(blank=True, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('screening_session', models.OneToOneField(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='pca_pipeline_result', to='mindspace.platformscreeningsession')),
            ],
            options={
                'db_table': 'pca_pipeline_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FusionPrediction',
            fields=[
                ('prediction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anxiety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stress_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bipolar_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('suicidal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_risk', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('final_prediction_json', models.JSONField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('pca_result', models.OneToOneField(blank=True, db_column='pca_result_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fusion_prediction', to='mindspace.pcapipelineresult')),
                ('screening_session', models.OneToOneField(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='fusion_prediction', to='mindspace.platformscreeningsession')),
            ],
            options={
                'db_table': 'fusion_predictions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiExecutionLog',
            fields=[
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='mindspace.aiapiregistry')),
                ('screening_session', models.ForeignKey(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_execution_logs', to='mindspace.platformscreeningsession')),
            ],
            options={
                'db_table': 'api_execution_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScenarioSession',
            fields=[
                ('scenario_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_scenario', models.ForeignKey(db_column='audio_scenario_id', on_delete=django.db.models.deletion.PROTECT, related_name='scenario_sessions', to='mindspace.audioscenario')),
                ('media', models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_sessions', to='mindspace.mediaasset')),
                ('screening_session', models.ForeignKey(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sessions', to='mindspace.platformscreeningsession')),
            ],
            options={
                'db_table': 'scenario_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('security_event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TextAnalysisResult',
            fields=[
                ('text_analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anxiety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('text_parameter', models.OneToOneField(db_column='text_parameter_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_analysis_result', to='mindspace.textparameterresult')),
            ],
            options={
                'db_table': 'text_analysis_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_text', models.TextField()),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('transcript_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario_session', models.OneToOneField(db_column='scenario_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='mindspace.scenariosession')),
            ],
            options={
                'db_table': 'transcripts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='textparameterresult',
            name='transcript',
            field=models.OneToOneField(db_column='transcript_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_parameter_result', to='mindspace.transcript'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('counselor', 'Counselor'), ('researcher', 'Researcher')], default='user', max_length=20)),
                ('account_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('consented', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': True,
                'indexes': [models.Index(fields=['role'], name='idx_user_profiles_role'), models.Index(fields=['account_status'], name='idx_user_profiles_status')],
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('video_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('session_status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_sessions', to='mindspace.mediaasset')),
                ('screening_session', models.ForeignKey(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='mindspace.platformscreeningsession')),
                ('video_activity', models.ForeignKey(db_column='video_activity_id', on_delete=django.db.models.deletion.PROTECT, related_name='video_sessions', to='mindspace.videoactivity')),
            ],
            options={
                'db_table': 'video_sessions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facefeaturevector',
            name='video_session',
            field=models.ForeignKey(db_column='video_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='face_feature_vectors', to='mindspace.videosession'),
        ),
        migrations.CreateModel(
            name='VoiceAnalysisResult',
            fields=[
                ('voice_analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speech_impairment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.OneToOneField(db_column='feature_id', on_delete=django.db.models.deletion.CASCADE, related_name='voice_analysis_result', to='mindspace.phonationfeature')),
            ],
            options={
                'db_table': 'voice_analysis_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModalityResult',
            fields=[
                ('modality_result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('face', 'Face'), ('voice', 'Voice'), ('text', 'Text')], max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_result', models.OneToOneField(blank=True, db_column='face_result_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modality_result', to='mindspace.facialanalysisresult')),
                ('screening_session', models.ForeignKey(db_column='screening_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='modality_results', to='mindspace.platformscreeningsession')),
                ('text_result', models.OneToOneField(blank=True, db_column='text_result_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modality_result', to='mindspace.textanalysisresult')),
                ('voice_result', models.OneToOneField(blank=True, db_column='voice_result_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modality_result', to='mindspace.voiceanalysisresult')),
            ],
            options={
                'db_table': 'modality_results',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='facialanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stress_score__gte', 0), ('stress_score__lte', 100)), ('stress_score__isnull', True), _connector='OR'), name='face_stress_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='facialanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depression_score__gte', 0), ('depression_score__lte', 100)), ('depression_score__isnull', True), _connector='OR'), name='face_depression_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='facialanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anxiety_score__gte', 0), ('anxiety_score__lte', 100)), ('anxiety_score__isnull', True), _connector='OR'), name='face_anxiety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='facialanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), ('confidence_score__isnull', True), _connector='OR'), name='face_confidence_score_0_1'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['user', '-created_at'], name='idx_media_assets_user_created'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='media_size_bytes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 0), ('duration_seconds__isnull', True), _connector='OR'), name='media_duration_seconds_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='phonationattempt',
            constraint=models.UniqueConstraint(fields=('phonation_session', 'sound'), name='unique_phonation_session_sound'),
        ),
        migrations.AddConstraint(
            model_name='phonationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character_accuracy_score__gte', 0), ('character_accuracy_score__lte', 100)), ('character_accuracy_score__isnull', True), _connector='OR'), name='phonation_accuracy_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='phonationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('silence_duration_ms__gte', 0), ('silence_duration_ms__isnull', True), _connector='OR'), name='phonation_silence_duration_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='phonationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('response_time_ms__gte', 0), ('response_time_ms__isnull', True), _connector='OR'), name='phonation_response_time_gte_0'),
        ),
        migrations.AddIndex(
            model_name='platformscreeningsession',
            index=models.Index(fields=['user', '-started_at'], name='idx_screening_user_created'),
        ),
        migrations.AddConstraint(
            model_name='platformscreeningsession',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_stage__gte', 1)), name='screening_workflow_stage_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='platformscreeningsession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_activities_count__gte', 0)), name='screening_completed_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anxiety_score__gte', 0), ('anxiety_score__lte', 100)), ('anxiety_score__isnull', True), _connector='OR'), name='fusion_anxiety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depression_score__gte', 0), ('depression_score__lte', 100)), ('depression_score__isnull', True), _connector='OR'), name='fusion_depression_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stress_score__gte', 0), ('stress_score__lte', 100)), ('stress_score__isnull', True), _connector='OR'), name='fusion_stress_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bipolar_score__gte', 0), ('bipolar_score__lte', 100)), ('bipolar_score__isnull', True), _connector='OR'), name='fusion_bipolar_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('suicidal_score__gte', 0), ('suicidal_score__lte', 100)), ('suicidal_score__isnull', True), _connector='OR'), name='fusion_suicidal_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='fusionprediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), ('confidence_score__isnull', True), _connector='OR'), name='fusion_confidence_score_0_1'),
        ),
        migrations.AddIndex(
            model_name='apiexecutionlog',
            index=models.Index(fields=['screening_session', '-created_at'], name='idx_api_logs_screening'),
        ),
        migrations.AddConstraint(
            model_name='apiexecutionlog',
            constraint=models.CheckConstraint(condition=models.Q(('processing_time_ms__gte', 0), ('processing_time_ms__isnull', True), _connector='OR'), name='api_processing_time_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='textanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stress_score__gte', 0), ('stress_score__lte', 100)), ('stress_score__isnull', True), _connector='OR'), name='text_stress_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='textanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depression_score__gte', 0), ('depression_score__lte', 100)), ('depression_score__isnull', True), _connector='OR'), name='text_depression_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='textanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anxiety_score__gte', 0), ('anxiety_score__lte', 100)), ('anxiety_score__isnull', True), _connector='OR'), name='text_anxiety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='textanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), ('confidence_score__isnull', True), _connector='OR'), name='text_confidence_score_0_1'),
        ),
        migrations.AddConstraint(
            model_name='textparameterresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sentiment_score__gte', -100), ('sentiment_score__lte', 100)), ('sentiment_score__isnull', True), _connector='OR'), name='text_sentiment_score_minus100_100'),
        ),
        migrations.AddConstraint(
            model_name='facefeaturevector',
            constraint=models.CheckConstraint(condition=models.Q(('frame_number__gte', 0)), name='face_frame_number_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facefeaturevector',
            constraint=models.CheckConstraint(condition=models.Q(('blink_rate__gte', 0), ('blink_rate__isnull', True), _connector='OR'), name='face_blink_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='voiceanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stress_score__gte', 0), ('stress_score__lte', 100)), ('stress_score__isnull', True), _connector='OR'), name='voice_stress_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='voiceanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depression_score__gte', 0), ('depression_score__lte', 100)), ('depression_score__isnull', True), _connector='OR'), name='voice_depression_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='voiceanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('speech_impairment_score__gte', 0), ('speech_impairment_score__lte', 100)), ('speech_impairment_score__isnull', True), _connector='OR'), name='voice_speech_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='voiceanalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), ('confidence_score__isnull', True), _connector='OR'), name='voice_confidence_score_0_1'),
        ),
        migrations.AddConstraint(
            model_name='modalityresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), ('confidence_score__isnull', True), _connector='OR'), name='modality_confidence_score_0_1'),
        ),
    ]
