# Generated by Django 6.0.4 on 2026-05-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_1.png', max_length=100, null=True),
        ),
    ]
